# Generated by Django 5.1.1 on 2024-10-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_logentry_userwithaccess_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithaccess',
            name='chip_identifier',
            field=models.BinaryField(max_length=4),
        ),
    ]
